import { supabase } from '../integrations/supabase/client'
export async function loadCommercialData(){const [leads,clients,quotes,quoteItems,contracts,events,inventory,reservations,tasks,finance,payments]=await Promise.all([supabase.from('leads').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('clients').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('quotes').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('quote_items').select('*').order('display_order'),supabase.from('contracts').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('events').select('*').order('event_date',{ascending:true}).limit(100),supabase.from('inventory_items').select('*').eq('active',true).order('name'),supabase.from('inventory_reservations').select('*').order('reserved_from',{ascending:true}),supabase.from('event_tasks').select('*').order('due_at',{ascending:true}),supabase.from('financial_entries').select('*').order('due_date',{ascending:true}),supabase.from('financial_payments').select('*').order('paid_at',{ascending:false}).limit(200)]);const all=[leads,clients,quotes,quoteItems,contracts,events,inventory,reservations,tasks,finance,payments],error=all.find(x=>x.error)?.error;if(error)throw error;return{leads:leads.data??[],clients:clients.data??[],quotes:quotes.data??[],quoteItems:quoteItems.data??[],contracts:contracts.data??[],events:events.data??[],inventory:inventory.data??[],reservations:reservations.data??[],tasks:tasks.data??[],finance:finance.data??[],payments:payments.data??[]}}
export async function createLead(companyId:string,input:Record<string,string>){const{data,error}=await supabase.from('leads').insert({company_id:companyId,name:input.name,phone:input.phone,email:input.email||null,city:input.city||null,event_type:input.eventType||null,event_date:input.eventDate||null,notes:input.notes||null,status:'novo'}).select().single();if(error)throw error;return data}
export async function createQuoteFromLead(leadId:string){const{data,error}=await supabase.rpc('create_quote_from_lead',{target_lead_id:leadId});if(error)throw error;return data}
export async function convertLeadToClient(leadId:string){const{data,error}=await supabase.rpc('convert_lead_to_client',{target_lead_id:leadId});if(error)throw error;return data}
export async function addQuoteItem(companyId:string,quoteId:string,input:Record<string,string>){const{error}=await supabase.from('quote_items').insert({company_id:companyId,quote_id:quoteId,item_type:input.itemType||'servico',description:input.description,quantity:Number(input.quantity||1),unit_price:Number(String(input.unitPrice||0).replace(',','.'))});if(error)throw error}
export async function removeQuoteItem(id:string){const{error}=await supabase.from('quote_items').delete().eq('id',id);if(error)throw error}
export async function setQuoteStatus(quoteId:string,status:string){const{error}=await supabase.from('quotes').update({status,updated_at:new Date().toISOString()}).eq('id',quoteId);if(error)throw error}
export async function createContract(quoteId:string){const{data,error}=await supabase.rpc('create_contract_from_approved_quote',{target_quote_id:quoteId});if(error)throw error;return data}
export async function createEvent(contractId:string,input:Record<string,string>){const{data,error}=await supabase.rpc('create_event_from_contract',{target_contract_id:contractId,event_date:input.eventDate,event_time:input.eventTime||null,event_address:input.address||null,event_city:input.city||null,event_state:input.state||null});if(error)throw error;return data}
export async function markContractSigned(contractId:string){const{error}=await supabase.from('contracts').update({status:'assinado'}).eq('id',contractId);if(error)throw error}
export async function createInventoryItem(companyId:string,input:Record<string,string>){const{error}=await supabase.from('inventory_items').insert({company_id:companyId,name:input.name,quantity_total:Number(input.quantity||1),category:input.category||null,notes:input.notes||null,active:true});if(error)throw error}
export async function reserveInventory(companyId:string,eventId:string,itemId:string,quantity:number,from:string,until:string){const{error}=await supabase.from('inventory_reservations').insert({company_id:companyId,event_id:eventId,item_id:itemId,quantity,reserved_from:from,reserved_until:until});if(error)throw error}
export async function addEventTask(companyId:string,eventId:string,input:Record<string,string>){const{error}=await supabase.from('event_tasks').insert({company_id:companyId,event_id:eventId,title:input.title,category:input.category||'operacao',due_at:input.dueAt||null,notes:input.notes||null});if(error)throw error}
export async function completeEventTask(id:string,done:boolean){const{error}=await supabase.from('event_tasks').update({completed_at:done?new Date().toISOString():null}).eq('id',id);if(error)throw error}
export async function createFinancialEntry(companyId:string,input:Record<string,string>){const{data,error}=await supabase.from('financial_entries').insert({company_id:companyId,kind:input.direction||'receber',category:input.category||'outro',description:input.description,amount:Number(String(input.amount||0).replace(',','.')),due_date:input.dueDate||null,status:'pendente',is_refundable_deposit:input.refundable==='on'}).select().single();if(error)throw error;return data}
export async function registerPayment(companyId:string,entryId:string,amount:number,method?:string){const{data:entry,error:e}=await supabase.from('financial_entries').select('amount').eq('id',entryId).single();if(e)throw e;const{data:paid,error:p}=await supabase.from('financial_payments').select('amount').eq('entry_id',entryId);if(p)throw p;const already=(paid??[]).reduce((s:number,x:any)=>s+Number(x.amount||0),0),next=already+amount;if(next>Number(entry.amount))throw new Error('O pagamento ultrapassa o valor do lançamento.');const{error}=await supabase.from('financial_payments').insert({company_id:companyId,entry_id:entryId,amount,method:method||null,paid_at:new Date().toISOString()});if(error)throw error;const status=next>=Number(entry.amount)?'pago':next>0?'parcial':'pendente';const u=await supabase.from('financial_entries').update({status}).eq('id',entryId);if(u.error)throw u.error}
export function money(value:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value||0)}
export function shortDate(value:string|null){if(!value)return '—';return value.slice(0,10).split('-').reverse().join('/')}
