import { supabase } from '../integrations/supabase/client'
export async function loadCommercialData(){const [leads,clients,quotes,quoteItems,contracts,events,inventory,reservations,checks,production,logistics,today]=await Promise.all([supabase.from('leads').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('clients').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('quotes').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('quote_items').select('*').order('display_order'),supabase.from('contracts').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('events').select('*').order('starts_at',{ascending:true}).limit(100),supabase.from('inventory_items').select('*').eq('status','ativo').order('name'),supabase.from('inventory_reservations').select('*').order('reserved_from',{ascending:true}),supabase.from('inventory_checks').select('*').order('created_at'),supabase.from('production_board').select('*').order('separation_due_at',{ascending:true}),supabase.from('logistics_runs').select('*').order('scheduled_at',{ascending:true}),supabase.from('today_actions').select('*').order('scheduled_at',{ascending:true})]);const all=[leads,clients,quotes,quoteItems,contracts,events,inventory,reservations,checks,production,logistics,today];const error=all.find(x=>x.error)?.error;if(error)throw error;return{leads:leads.data??[],clients:clients.data??[],quotes:quotes.data??[],quoteItems:quoteItems.data??[],contracts:contracts.data??[],events:events.data??[],inventory:inventory.data??[],reservations:reservations.data??[],checks:checks.data??[],production:production.data??[],logistics:logistics.data??[],today:today.data??[]}}
export async function createLead(companyId:string,input:Record<string,string>){const{data,error}=await supabase.from('leads').insert({company_id:companyId,name:input.name,phone:input.phone,email:input.email||null,city:input.city||null,event_type:input.eventType||null,event_date:input.eventDate||null,notes:input.notes||null,status:'novo'}).select().single();if(error)throw error;return data}
export async function createQuoteFromLead(leadId:string){const{data,error}=await supabase.rpc('create_quote_from_lead',{target_lead_id:leadId});if(error)throw error;return data}
export async function convertLeadToClient(leadId:string){const{data,error}=await supabase.rpc('convert_lead_to_client',{target_lead_id:leadId});if(error)throw error;return data}
export async function addQuoteItem(companyId:string,quoteId:string,input:Record<string,string>){const quantity=Number(input.quantity||1),unit=Number(String(input.unitPrice||0).replace(',','.'));const{error}=await supabase.from('quote_items').insert({company_id:companyId,quote_id:quoteId,item_type:input.itemType||'servico',description:input.description,quantity,unit_price:unit});if(error)throw error;await recalcQuote(quoteId)}
export async function removeQuoteItem(id:string,quoteId:string){const{error}=await supabase.from('quote_items').delete().eq('id',id);if(error)throw error;await recalcQuote(quoteId)}
async function recalcQuote(quoteId:string){const{data,error}=await supabase.from('quote_items').select('total').eq('quote_id',quoteId);if(error)throw error;const subtotal=(data??[]).reduce((s:number,x:any)=>s+Number(x.total||0),0);const q=await supabase.from('quotes').select('discount').eq('id',quoteId).single();if(q.error)throw q.error;const total=Math.max(0,subtotal-Number(q.data.discount||0));const u=await supabase.from('quotes').update({subtotal,total,updated_at:new Date().toISOString()}).eq('id',quoteId);if(u.error)throw u.error}
export async function setQuoteStatus(quoteId:string,status:string){const patch:Record<string,any>={status,updated_at:new Date().toISOString()};if(status==='enviado')patch.sent_at=new Date().toISOString();if(status==='aprovado')patch.approved_at=new Date().toISOString();const{error}=await supabase.from('quotes').update(patch).eq('id',quoteId);if(error)throw error}
export async function createContract(quoteId:string){const{data,error}=await supabase.rpc('create_contract_from_quote',{target_quote_id:quoteId});if(error)throw error;return data}
export async function activateContract(contractId:string){const{data,error}=await supabase.rpc('activate_contract_and_create_event',{target_contract_id:contractId});if(error)throw error;return data}
export async function createInventoryItem(companyId:string,input:Record<string,string>){const{error}=await supabase.from('inventory_items').insert({company_id:companyId,name:input.name,total_quantity:Number(input.quantity||1),replacement_cost:input.cost?Number(String(input.cost).replace(',','.')):null,status:'ativo'});if(error)throw error}
export async function reserveInventory(eventId:string,itemId:string,quantity:number,from:string,until:string){const{data,error}=await supabase.rpc('reserve_inventory_item',{target_event_id:eventId,target_item_id:itemId,requested_quantity:quantity,period_from:from,period_until:until});if(error)throw error;return data}
export async function prepareProduction(eventId:string){const{data,error}=await supabase.rpc('prepare_event_for_production',{target_event_id:eventId,due_at:null});if(error)throw error;return data}
export async function setInventoryCheck(checkId:string,status:string,checkedQuantity:number){const{error}=await supabase.from('inventory_checks').update({status,checked_quantity:checkedQuantity,checked_at:new Date().toISOString()}).eq('id',checkId);if(error)throw error}
export async function markProductionReady(orderId:string){const{error}=await supabase.rpc('mark_production_ready',{target_order_id:orderId});if(error)throw error}
export async function syncLogistics(eventId:string){const{data,error}=await supabase.rpc('sync_event_logistics',{target_event_id:eventId});if(error)throw error;return data}
export async function setLogisticsStatus(runId:string,status:string){const patch:Record<string,any>={status,updated_at:new Date().toISOString()};if(status==='em_rota')patch.started_at=new Date().toISOString();if(status==='no_local')patch.arrived_at=new Date().toISOString();if(status==='concluido')patch.completed_at=new Date().toISOString();const{error}=await supabase.from('logistics_runs').update(patch).eq('id',runId);if(error)throw error}
export async function prepareReturn(eventId:string){const{data,error}=await supabase.rpc('prepare_event_inventory_check',{target_event_id:eventId,target_phase:'devolucao'});if(error)throw error;return data}
export async function closeEvent(eventId:string){const{error}=await supabase.rpc('close_event_operation',{target_event_id:eventId});if(error)throw error}
export function money(value:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value||0)}
export function shortDate(value:string|null){if(!value)return '—';return value.slice(0,10).split('-').reverse().join('/')}
