import {supabase} from '../integrations/supabase/client'
export async function loadSettingsData(companyId:string){const [company,settings,members,modalities,packages,rules,subscription,invites]=await Promise.all([supabase.rpc('my_company_profile',{target_company_id:companyId}),supabase.rpc('my_company_settings',{target_company_id:companyId}),supabase.rpc('my_company_members',{target_company_id:companyId}),supabase.from('business_modalities').select('*').eq('company_id',companyId).order('display_order'),supabase.from('service_packages').select('*').eq('company_id',companyId).order('display_order'),supabase.from('business_rules').select('*').eq('company_id',companyId),supabase.rpc('my_subscription_context',{target_company_id:companyId}),supabase.rpc('my_company_invite_links',{target_company_id:companyId})]);const all=[company,settings,members,modalities,packages,rules,subscription,invites],error=all.find(x=>x.error)?.error;if(error)throw error;const companyData=Array.isArray(company.data)?company.data[0]:company.data;const settingsData=Array.isArray(settings.data)?settings.data[0]:settings.data;const subscriptionData=Array.isArray(subscription.data)?subscription.data[0]:subscription.data;return{company:companyData,settings:settingsData,members:members.data??[],profiles:members.data??[],modalities:modalities.data??[],packages:packages.data??[],rules:rules.data??[],subscription:subscriptionData,invites:invites.data??[]}}
export async function saveCompany(companyId:string,input:Record<string,string>){const{error}=await supabase.rpc('update_company_profile',{target_company_id:companyId,new_name:input.name,new_legal_name:input.legalName||null,new_document:input.document||null,new_responsible_name:input.responsibleName||null,new_email:input.email||null,new_whatsapp:input.whatsapp||null,new_instagram:input.instagram||null,new_city:input.city||null,new_state:input.state||null});if(error)throw error}
export async function ensureSettings(companyId:string){const{error}=await supabase.rpc('ensure_my_company_settings',{target_company_id:companyId});if(error)throw error}
export async function saveSettings(companyId:string,input:Record<string,string>){await ensureSettings(companyId);const{error}=await supabase.rpc('update_my_company_settings',{target_company_id:companyId,new_currency:input.currency||'BRL',new_timezone:input.timezone||'America/Sao_Paulo',new_buffer_minutes:Number(input.buffer||0),new_settings:{quote_validity_days:Number(input.quoteValidity||0),default_notes:input.defaultNotes||'',operation_notes:input.operationNotes||''}});if(error)throw error}
export async function addModality(companyId:string,input:Record<string,string>){const{error}=await supabase.from('business_modalities').insert({company_id:companyId,name:input.name,description:input.description||null,requires_pickup:input.requiresPickup==='on',requires_return:input.requiresReturn==='on',allows_delivery:input.allowsDelivery==='on',includes_setup:input.includesSetup==='on',includes_teardown:input.includesTeardown==='on'});if(error)throw error}
export async function addPackage(companyId:string,input:Record<string,string>){const{error}=await supabase.from('service_packages').insert({company_id:companyId,modality_id:input.modalityId||null,name:input.name,description:input.description||null,suggested_price:input.price?Number(input.price.replace(',','.')):null,allow_manual_price:true,customer_notes:input.customerNotes||null,internal_notes:input.internalNotes||null});if(error)throw error}
export async function addBusinessRule(companyId:string,input:Record<string,string>){const{error}=await supabase.from('business_rules').insert({company_id:companyId,modality_id:input.modalityId||null,package_id:input.packageId||null,signal_type:input.signalType||'percent',signal_value:input.signalValue?Number(input.signalValue.replace(',','.')):null,final_payment_days_before:input.finalDays?Number(input.finalDays):null,quote_validity_days:input.validity?Number(input.validity):null,reservation_confirmation:input.confirmation||'signal',deposit_mode:input.depositMode||'none',deposit_value:input.depositValue?Number(input.depositValue.replace(',','.')):null,late_fee_value:input.lateFee?Number(input.lateFee.replace(',','.')):null,cancellation_policy:input.cancellation||null});if(error)throw error}
export async function inviteMember(companyId:string,email:string,role:string){const{data,error}=await supabase.rpc('create_company_invite',{target_company_id:companyId,target_email:email.trim().toLowerCase(),target_role:role});if(error)throw error;return data}
export async function cancelInvitation(companyId:string,id:string){const{error}=await supabase.rpc('cancel_company_invite',{target_company_id:companyId,target_invite_id:id});if(error)throw error}
export async function setMemberRole(companyId:string,userId:string,role:string,active=true){const{error}=await supabase.rpc('update_company_member',{target_company_id:companyId,target_user_id:userId,new_role:role,new_active:active});if(error)throw error}
export async function setMemberActive(companyId:string,userId:string,active:boolean,role:string){const{error}=await supabase.rpc('update_company_member',{target_company_id:companyId,target_user_id:userId,new_role:role,new_active:active});if(error)throw error}

export async function setModalityActive(id:string,active:boolean){const{error}=await supabase.from('business_modalities').update({active}).eq('id',id);if(error)throw error}
export async function setPackageActive(id:string,active:boolean){const{error}=await supabase.from('service_packages').update({active}).eq('id',id);if(error)throw error}
export async function setRuleActive(id:string,active:boolean){const{error}=await supabase.from('business_rules').update({active}).eq('id',id);if(error)throw error}
