import {supabase} from '../integrations/supabase/client'
export async function loadSettingsData(companyId:string){const [company,settings,members,profiles,modalities,packages,rules,subscription]=await Promise.all([supabase.from('companies').select('*').eq('id',companyId).single(),supabase.from('company_settings').select('*').eq('company_id',companyId).maybeSingle(),supabase.from('company_members').select('*').eq('company_id',companyId).order('created_at'),supabase.from('profiles').select('*'),supabase.from('business_modalities').select('*').eq('company_id',companyId).order('display_order'),supabase.from('service_packages').select('*').eq('company_id',companyId).order('display_order'),supabase.from('business_rules').select('*').eq('company_id',companyId),supabase.from('company_subscriptions').select('*').eq('company_id',companyId).maybeSingle()]);const all=[company,settings,members,profiles,modalities,packages,rules,subscription];const error=all.find(x=>x.error)?.error;if(error)throw error;return{company:company.data,settings:settings.data,members:members.data??[],profiles:profiles.data??[],modalities:modalities.data??[],packages:packages.data??[],rules:rules.data??[],subscription:subscription.data}}
export async function saveCompany(companyId:string,input:Record<string,string>){const{error}=await supabase.from('companies').update({name:input.name,legal_name:input.legalName||null,document:input.document||null,responsible_name:input.responsibleName||null,email:input.email||null,whatsapp:input.whatsapp||null,instagram:input.instagram||null,city:input.city||null,state:input.state||null,updated_at:new Date().toISOString()}).eq('id',companyId);if(error)throw error}
export async function ensureSettings(companyId:string){const{error}=await supabase.rpc('ensure_my_company_settings',{target_company_id:companyId});if(error)throw error}
export async function saveSettings(companyId:string,input:Record<string,string>){await ensureSettings(companyId);const{error}=await supabase.from('company_settings').update({currency:input.currency||'BRL',timezone:input.timezone||'America/Sao_Paulo',reservation_buffer_minutes:Number(input.buffer||0),settings:{quote_validity_days:Number(input.quoteValidity||0),default_notes:input.defaultNotes||'',operation_notes:input.operationNotes||''},updated_at:new Date().toISOString()}).eq('company_id',companyId);if(error)throw error}
export async function addModality(companyId:string,input:Record<string,string>){const{error}=await supabase.from('business_modalities').insert({company_id:companyId,name:input.name,description:input.description||null,requires_pickup:input.requiresPickup==='on',requires_return:input.requiresReturn==='on',allows_delivery:input.allowsDelivery==='on',includes_setup:input.includesSetup==='on',includes_teardown:input.includesTeardown==='on'});if(error)throw error}
export async function addPackage(companyId:string,input:Record<string,string>){const{error}=await supabase.from('service_packages').insert({company_id:companyId,modality_id:input.modalityId||null,name:input.name,description:input.description||null,suggested_price:input.price?Number(input.price.replace(',','.')):null,allow_manual_price:true,customer_notes:input.customerNotes||null,internal_notes:input.internalNotes||null});if(error)throw error}
export async function addBusinessRule(companyId:string,input:Record<string,string>){const{error}=await supabase.from('business_rules').insert({company_id:companyId,modality_id:input.modalityId||null,package_id:input.packageId||null,signal_type:input.signalType||'percent',signal_value:input.signalValue?Number(input.signalValue.replace(',','.')):null,final_payment_days_before:input.finalDays?Number(input.finalDays):null,quote_validity_days:input.validity?Number(input.validity):null,reservation_confirmation:input.confirmation||'signal',deposit_mode:input.depositMode||'none',deposit_value:input.depositValue?Number(input.depositValue.replace(',','.')):null,late_fee_value:input.lateFee?Number(input.lateFee.replace(',','.')):null,cancellation_policy:input.cancellation||null});if(error)throw error}
export async function setMemberRole(memberId:string,role:string){const{error}=await supabase.from('company_members').update({role,updated_at:new Date().toISOString()}).eq('id',memberId);if(error)throw error}
export async function setMemberActive(memberId:string,active:boolean){const{error}=await supabase.from('company_members').update({active,updated_at:new Date().toISOString()}).eq('id',memberId);if(error)throw error}
