import { createFileRoute, Link, useNavigate } from '@tanstack/react-router'
import { FormEvent, useEffect, useMemo, useState } from 'react'
import { supabase } from '../integrations/supabase/client'
import { convertLeadToClient, createLead, createQuoteFromLead, loadCommercialData, money, shortDate, updateQuoteTotal } from '../lib/erp-data'

export const Route=createFileRoute('/app')({component:Workspace})
type Context={company_id:string;company_name:string;company_status:string;role:string;trial_ends_at:string|null;days_remaining:number|null;access_allowed:boolean}
type Row=Record<string,any>
const modules=['Hoje','CRM e Leads','Clientes','Orçamentos','Contratos','Agenda e Eventos','Estoque','Produção','Logística','Financeiro','Gestão','Configurações']

function Workspace(){
 const navigate=useNavigate();const[ctx,setCtx]=useState<Context|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[active,setActive]=useState('Hoje');const[leads,setLeads]=useState<Row[]>([]);const[clients,setClients]=useState<Row[]>([]);const[quotes,setQuotes]=useState<Row[]>([]);const[busy,setBusy]=useState('');const[showLead,setShowLead]=useState(false)
 useEffect(()=>{void boot()},[])
 async function boot(){const{data:{user}}=await supabase.auth.getUser();if(!user){navigate({to:'/entrar'});return}await supabase.rpc('activate_my_pending_trial');const{data,error:e}=await supabase.rpc('my_company_context');if(e){setError(e.message);setLoading(false);return}const row=(Array.isArray(data)?data[0]:data) as Context|undefined;if(!row){setLoading(false);return}setCtx(row);if(row.access_allowed)await refresh();setLoading(false)}
 async function refresh(){try{const data=await loadCommercialData();setLeads(data.leads);setClients(data.clients);setQuotes(data.quotes)}catch(e:any){setError(e.message||'Falha ao carregar dados') }}
 async function logout(){await supabase.auth.signOut();navigate({to:'/entrar'})}
 async function submitLead(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!ctx)return;setBusy('lead');const fd=new FormData(e.currentTarget);try{await createLead(ctx.company_id,Object.fromEntries(fd.entries()) as Record<string,string>);e.currentTarget.reset();setShowLead(false);await refresh()}catch(err:any){setError(err.message)}finally{setBusy('')}}
 async function quoteFromLead(id:string){setBusy(id);try{await createQuoteFromLead(id);await refresh();setActive('Orçamentos')}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function clientFromLead(id:string){setBusy(id);try{await convertLeadToClient(id);await refresh();setActive('Clientes')}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function setQuoteValue(q:Row){const raw=window.prompt('Valor total do orçamento',String(q.total||0));if(raw==null)return;const value=Number(raw.replace(',','.'));if(Number.isNaN(value)||value<0)return;setBusy(q.id);try{await updateQuoteTotal(q.id,value);await refresh()}catch(e:any){setError(e.message)}finally{setBusy('')}}
 const openQuotes=quotes.filter(q=>!['recusado','cancelado','expirado'].includes(q.status));const totalQuotes=useMemo(()=>openQuotes.reduce((s,q)=>s+Number(q.total||0),0),[quotes]);const newLeads=leads.filter(l=>l.status==='novo');
 if(loading)return <div className="app-gate">Carregando seu ambiente Heaven...</div>
 if(error&&!ctx)return <div className="app-gate"><div><h1>Não encontramos seu ambiente.</h1><p>{error}</p><Link to="/entrar" className="primary-link">Voltar ao acesso</Link></div></div>
 if(!ctx)return <div className="app-gate">Ambiente não encontrado.</div>
 if(!ctx.access_allowed)return <div className="app-gate"><div><span className="tag">Período encerrado</span><h1>Seu ambiente está preservado.</h1><p>O teste terminou. Seus dados continuam seguros e serão liberados quando a assinatura for ativada.</p><button className="primary" onClick={logout}>Sair</button></div></div>
 return <div className="heaven-shell">
  <aside className="heaven-sidebar"><div className="heaven-brand">heaven <small>PLATAFORMA</small></div><nav className="heaven-nav">{modules.map(x=><button onClick={()=>setActive(x)} className={active===x?'active':''} key={x}>{x}</button>)}</nav><div className="heaven-company"><b>{ctx.company_name}</b><br/>{ctx.role}</div></aside>
  <main className="heaven-main"><header className="heaven-header"><div><span className="heaven-eyebrow">{ctx.company_name}</span><h1 className="heaven-title">{active}</h1><span className="heaven-muted">{subtitle(active)}</span></div><div className="workspace-actions">{ctx.days_remaining!=null&&<span className="trial-counter">Teste · {ctx.days_remaining} dias restantes</span>}<button onClick={logout} className="secondary-link">Sair</button></div></header>
   {error&&<div className="heaven-alert"><b>Atenção</b><span>{error}</span><button onClick={()=>setError('')}>×</button></div>}
   {active==='Hoje'&&<Today leads={leads} quotes={quotes} clients={clients} totalQuotes={totalQuotes} onLead={()=>setShowLead(true)} onOpen={setActive}/>} 
   {active==='CRM e Leads'&&<Leads leads={leads} busy={busy} onNew={()=>setShowLead(true)} onQuote={quoteFromLead} onClient={clientFromLead}/>} 
   {active==='Clientes'&&<Clients rows={clients}/>} 
   {active==='Orçamentos'&&<Quotes rows={quotes} busy={busy} onValue={setQuoteValue}/>} 
   {!['Hoje','CRM e Leads','Clientes','Orçamentos'].includes(active)&&<Coming module={active}/>} 
  </main>
  <nav className="heaven-mobile-nav">{modules.slice(0,5).map(x=><button key={x} className={active===x?'active':''} onClick={()=>setActive(x)}>{x}</button>)}</nav>
  {showLead&&<LeadModal busy={busy==='lead'} onClose={()=>setShowLead(false)} onSubmit={submitLead}/>} 
 </div>
}
function subtitle(x:string){return x==='Hoje'?'O que precisa da sua atenção agora.':x==='CRM e Leads'?'Organize oportunidades e transforme contatos em vendas.':x==='Clientes'?'Sua base de clientes, criada sem redigitação.':x==='Orçamentos'?'Propostas comerciais conectadas aos leads e clientes.':'Módulo preparado para a próxima etapa de integração.'}
function Today({leads,quotes,clients,totalQuotes,onLead,onOpen}:{leads:Row[];quotes:Row[];clients:Row[];totalQuotes:number;onLead:()=>void;onOpen:(x:string)=>void}){const novos=leads.filter(x=>x.status==='novo');return <><div className="heaven-grid heaven-kpis"><div className="heaven-card"><small>Novos leads</small><div className="heaven-value">{novos.length}</div></div><div className="heaven-card"><small>Orçamentos abertos</small><div className="heaven-value">{quotes.filter(x=>!['recusado','cancelado','expirado'].includes(x.status)).length}</div></div><div className="heaven-card"><small>Clientes</small><div className="heaven-value">{clients.length}</div></div><div className="heaven-card"><small>Em propostas</small><div className="heaven-value">{money(totalQuotes)}</div></div></div><div className="heaven-grid heaven-columns"><section className="heaven-card"><div className="card-head"><h2>Precisa da sua atenção</h2><button className="primary" onClick={onLead}>+ Novo lead</button></div>{novos.length===0?<Empty text="Nenhum lead novo. Cadastre o primeiro contato para iniciar o fluxo."/>:novos.slice(0,6).map(l=><div className="heaven-task" key={l.id}><span>●</span><div><b>{l.name}</b><small>{l.event_type||'Evento a definir'} · {shortDate(l.event_date)}</small></div><button onClick={()=>onOpen('CRM e Leads')}>Abrir</button></div>)}</section><section className="heaven-card"><h2>Fluxo comercial</h2><p className="heaven-muted">Lead → Orçamento → Cliente → Contrato. Cada informação segue adiante sem precisar ser digitada novamente.</p><div className="flow-stats"><b>{leads.length}</b><span>leads</span><b>{quotes.length}</b><span>orçamentos</span><b>{clients.length}</b><span>clientes</span></div></section></div></>}
function Leads({leads,busy,onNew,onQuote,onClient}:{leads:Row[];busy:string;onNew:()=>void;onQuote:(id:string)=>void;onClient:(id:string)=>void}){return <section className="heaven-card module-card"><div className="card-head"><div><h2>Leads</h2><span className="heaven-muted">{leads.length} contatos cadastrados</span></div><button className="primary" onClick={onNew}>+ Novo lead</button></div>{leads.length===0?<Empty text="Sua fila comercial está vazia."/>:<div className="table-scroll"><table className="heaven-table"><tbody>{leads.map(l=><tr key={l.id}><td><b>{l.name}</b><small>{l.phone||'Sem telefone'}</small></td><td>{l.event_type||'—'}</td><td>{shortDate(l.event_date)}</td><td><span className="heaven-status">{l.status}</span></td><td className="row-actions"><button disabled={busy===l.id} onClick={()=>onQuote(l.id)}>Orçamento</button><button disabled={busy===l.id} onClick={()=>onClient(l.id)}>Cliente</button></td></tr>)}</tbody></table></div>}</section>}
function Clients({rows}:{rows:Row[]}){return <section className="heaven-card module-card"><div className="card-head"><div><h2>Clientes</h2><span className="heaven-muted">Base criada a partir das conversões do CRM</span></div></div>{rows.length===0?<Empty text="Quando um lead for convertido, o cliente aparecerá aqui automaticamente."/>:<div className="table-scroll"><table className="heaven-table"><tbody>{rows.map(c=><tr key={c.id}><td><b>{c.name}</b><small>{c.email||'Sem e-mail'}</small></td><td>{c.phone||'—'}</td><td>{[c.city,c.state].filter(Boolean).join(' / ')||'—'}</td><td>{new Date(c.created_at).toLocaleDateString('pt-BR')}</td></tr>)}</tbody></table></div>}</section>}
function Quotes({rows,busy,onValue}:{rows:Row[];busy:string;onValue:(q:Row)=>void}){return <section className="heaven-card module-card"><div className="card-head"><div><h2>Orçamentos</h2><span className="heaven-muted">Propostas criadas diretamente dos leads</span></div></div>{rows.length===0?<Empty text="Crie um orçamento a partir de um lead para manter o histórico conectado."/>:<div className="table-scroll"><table className="heaven-table"><tbody>{rows.map(q=><tr key={q.id}><td><b>{q.title}</b><small>{shortDate(q.event_date)}</small></td><td><span className="heaven-status">{q.status}</span></td><td><b>{money(Number(q.total||0))}</b></td><td><button disabled={busy===q.id} onClick={()=>onValue(q)}>Definir valor</button></td></tr>)}</tbody></table></div>}</section>}
function Coming({module}:{module:string}){return <section className="heaven-card module-card"><span className="tag">Em integração</span><h2>{module}</h2><p className="heaven-muted">A estrutura deste módulo já existe no banco. Agora estamos conectando as telas em blocos grandes, preservando o mesmo fluxo de dados da empresa.</p></section>}
function Empty({text}:{text:string}){return <div className="empty-state"><b>Nada pendente por aqui.</b><span>{text}</span></div>}
function LeadModal({busy,onClose,onSubmit}:{busy:boolean;onClose:()=>void;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal-card" onMouseDown={e=>e.stopPropagation()}><div className="card-head"><div><span className="tag">Comercial</span><h2>Novo lead</h2></div><button className="modal-close" onClick={onClose}>×</button></div><form className="trial-form" onSubmit={onSubmit}><label>Nome<input required name="name" placeholder="Nome do cliente"/></label><div className="form-grid"><label>WhatsApp<input required name="phone" placeholder="(11) 99999-9999"/></label><label>E-mail<input name="email" type="email" placeholder="cliente@email.com"/></label></div><div className="form-grid"><label>Tipo de evento<input name="eventType" placeholder="Aniversário, casamento..."/></label><label>Data do evento<input name="eventDate" type="date"/></label></div><label>Cidade<input name="city" placeholder="Cidade do evento"/></label><label>Observações<input name="notes" placeholder="Tema, quantidade de convidados, referência..."/></label><button className="primary" disabled={busy}>{busy?'Salvando...':'Salvar lead'}</button></form></div></div>}
