import { createFileRoute, Link } from '@tanstack/react-router'
import { useState } from 'react'
export const Route=createFileRoute('/demo')({component:Demo})
const modules=['Hoje','CRM e Leads','Clientes','Orçamentos','Contratos','Agenda e Eventos','Estoque','Produção','Logística','Financeiro','Gestão','Configurações']
const rows:Record<string,string[][]>={'CRM e Leads':[['Mariana Alves','Aniversário infantil','Novo'],['Rafael Costa','Casamento','Orçamento']],Clientes:[['Mariana Alves','São Paulo','Ativo'],['Rafael Costa','Santo André','Ativo']],Orçamentos:[['#2051 · Mariana','R$ 1.350','Rascunho'],['#2049 · Rafael','R$ 4.800','Enviado']],Contratos:[['#1048 · Helena','R$ 1.480','Ativo'],['#1047 · Miguel','R$ 950','Ativo']], 'Agenda e Eventos':[['13 SET · Sofia','Entrega 10:00','Confirmado'],['14 SET · Miguel','Retirada 09:00','Confirmado']],Estoque:[['Painel romano','4 disponíveis','Ativo'],['Cilindro decorativo','8 disponíveis','Ativo']],Produção:[['Festa da Helena','18 de 25 itens','Em separação'],['15 anos · Sofia','25 de 25 itens','Pronto']],Logística:[['Sofia','13/09 · 10:00','Confirmado'],['Miguel','14/09 · 09:00','Planejado']],Financeiro:[['Contrato #1048','R$ 480','Vencido'],['Contrato #1047','R$ 650','Pendente']],Gestão:[['Recebido no mês','R$ 11.620','Realizado'],['Inadimplência','R$ 1.240','Atenção']],Configurações:[['Modalidades','3 cadastradas','Configurar'],['Equipe','4 usuários','Configurar']]}
function Demo(){const [active,setActive]=useState('Hoje');return <div className="heaven-shell"><aside className="heaven-sidebar"><div className="heaven-brand">heaven<small>PLATAFORMA</small></div><nav className="heaven-nav">{modules.map(m=><button key={m} className={active===m?'active':''} onClick={()=>setActive(m)}>{m}</button>)}</nav><div className="heaven-company"><b>Ambiente demonstração</b><br/><Link to="/">← Voltar ao site</Link></div></aside><main className="heaven-main"><header className="heaven-header"><div><div className="heaven-eyebrow">Heaven Plataforma</div><h1 className="heaven-title">{active}</h1><div className="heaven-muted">Dados fictícios para conhecer a experiência do sistema.</div></div><Link to="/testar" className="primary-link compact">Testar 15 dias</Link></header>{active==='Hoje'?<Today setActive={setActive}/>:<Page name={active}/>}</main><nav className="heaven-mobile-nav">{['Hoje','CRM e Leads','Agenda e Eventos','Produção','Financeiro','Gestão'].map(m=><button key={m} className={active===m?'active':''} onClick={()=>setActive(m)}>{m}</button>)}</nav></div>}
function Today({setActive}:{setActive:(x:string)=>void}){return <><div className="heaven-alert"><div><b>3 ações precisam de atenção hoje</b><div className="heaven-muted">Novo lead, separação pendente e recebimento vencido.</div></div><span className="heaven-pill">DEMO</span></div><div className="heaven-grid heaven-kpis">{[['Vendas do mês','R$ 18.450'],['Eventos do mês','R$ 15.900'],['Ticket médio','R$ 1.537'],['Conversão CRM','38,7%']].map(k=><section className="heaven-card" key={k[0]}><div className="heaven-muted">{k[0]}</div><div className="heaven-value">{k[1]}</div></section>)}</div><div className="heaven-grid heaven-columns"><section className="heaven-card"><h2>Tarefas de hoje</h2><Task t="Novo lead — Mariana Alves" s="Aniversário infantil · WhatsApp" a="Abrir CRM" go={()=>setActive('CRM e Leads')}/><Task t="Finalizar separação — Festa da Helena" s="18 de 25 itens conferidos" a="Produção" go={()=>setActive('Produção')}/><Task t="Recebimento vencido" s="Contrato #1048 · R$ 480" a="Financeiro" go={()=>setActive('Financeiro')}/></section><section className="heaven-card"><h2>Próximos eventos</h2><Task t="13 SET · 15 anos — Sofia" s="Entrega 10:00 · Montagem 11:30"/><Task t="14 SET · Chá de bebê — Miguel" s="Retirada 09:00 · Devolução 15/09"/></section></div></>}
function Task({t,s,a,go}:{t:string,s:string,a?:string,go?:()=>void}){return <div className="heaven-task"><div><b>{t}</b><div className="heaven-muted">{s}</div></div>{a&&<button onClick={go}>{a}</button>}</div>}
function Page({name}:{name:string}){const data=rows[name]||[];return <section className="heaven-card" style={{marginTop:22}}><h2>{name}</h2><table className="heaven-table"><tbody>{data.map((r,i)=><tr key={i}><td><b>{r[0]}</b></td><td>{r[1]}</td><td><span className="heaven-status">{r[2]}</span></td></tr>)}</tbody></table></section>}
