import { createFileRoute,Link,useNavigate } from '@tanstack/react-router'
import { useEffect,useState } from 'react'
import { supabase } from '../integrations/supabase/client'
import { loadCommercialData } from '../lib/erp-data'
import { loadFinanceManagement } from '../lib/management-data'
import { ActionCenter,FinanceModule,ManagementModule } from '../components/heaven/FinanceManagementModules'
export const Route=createFileRoute('/gestao')({component:ManagementWorkspace})
type Ctx={company_id:string;company_name:string;access_allowed:boolean}
function ManagementWorkspace(){const nav=useNavigate();const[ctx,setCtx]=useState<Ctx|null>(null),[erp,setErp]=useState<any>(null),[management,setManagement]=useState<any>(null),[tab,setTab]=useState('Hoje'),[busy,setBusy]=useState(''),[error,setError]=useState('');useEffect(()=>{void boot()},[]);async function boot(){const{data:{user}}=await supabase.auth.getUser();if(!user){nav({to:'/entrar'});return}const r=await supabase.rpc('my_company_context');if(r.error){setError(r.error.message);return}const c=(Array.isArray(r.data)?r.data[0]:r.data) as Ctx;if(!c?.access_allowed){nav({to:'/app'});return}setCtx(c);await refresh(c.company_id)}async function refresh(companyId=ctx?.company_id){if(!companyId)return;try{const[a,b]=await Promise.all([loadCommercialData(),loadFinanceManagement(companyId)]);setErp(a);setManagement(b)}catch(e:any){setError(e.message)}}async function run(id:string,fn:()=>Promise<any>){setBusy(id);try{await fn();await refresh()}catch(e:any){setError(e.message)}finally{setBusy('')}}if(!ctx||!erp||!management)return <div className="app-gate"><div><h1>Heaven Plataforma</h1><p>{error||'Carregando gestão...'}</p></div></div>;return <div className="heaven-main operations-page"><header className="heaven-header"><div><span className="heaven-eyebrow">{ctx.company_name}</span><h1 className="heaven-title">Central de gestão</h1><span className="heaven-muted">Hoje, financeiro e indicadores usando a mesma base operacional.</span></div><Link to="/app" className="secondary-link">← Voltar ao ERP</Link></header>{error&&<div className="heaven-alert"><b>Atenção</b><span>{error}</span><button onClick={()=>setError('')}>×</button></div>}<div className="workspace-tabs"><button className={tab==='Hoje'?'active':''} onClick={()=>setTab('Hoje')}>Hoje</button><button className={tab==='Financeiro'?'active':''} onClick={()=>setTab('Financeiro')}>Financeiro</button><button className={tab==='Gestão'?'active':''} onClick={()=>setTab('Gestão')}>Gestão</button></div>{tab==='Hoje'&&<ActionCenter erp={erp} management={management} go={x=>setTab(x==='Financeiro'?'Financeiro':x==='Gestão'?'Gestão':'Hoje')}/>} {tab==='Financeiro'&&<FinanceModule companyId={ctx.company_id} data={management} busy={busy} run={run}/>} {tab==='Gestão'&&<ManagementModule data={management}/>}</div>}
