import { createFileRoute } from '@tanstack/react-router'
import { useState } from 'react'

export const Route=createFileRoute('/')({component:HeavenDemo})

const modules=['Hoje','CRM e Leads','Clientes','Orçamentos','Contratos','Agenda e Eventos','Estoque','Produção','Logística','Financeiro','Gestão','Configurações']
const kpis=[['Vendas do mês','R$ 18.450','12 vendas aprovadas'],['Eventos do mês','R$ 15.900','9 eventos programados'],['Ticket médio','R$ 1.537','vendas ÷ quantidade'],['Conversão CRM','38,7%','12 de 31 leads']]
const rows:Record<string,string[][]>={
 'CRM e Leads':[['Mariana Alves','Aniversário infantil','Novo'],['Rafael Costa','Casamento','Orçamento'],['Fernanda Lima','15 anos','Negociação']],
 'Clientes':[['Mariana Alves','São Paulo','Ativo'],['Rafael Costa','Santo André','Ativo'],['Fernanda Lima','São Bernardo','Ativo']],
 'Orçamentos':[['#2051 · Mariana','R$ 1.350','Rascunho'],['#2049 · Rafael','R$ 4.800','Enviado'],['#2044 · Fernanda','R$ 2.100','Aprovado']],
 'Contratos':[['#1048 · Helena','R$ 1.480','Ativo'],['#1047 · Miguel','R$ 950','Ativo'],['#1044 · Sofia','R$ 2.100','Assinatura']],
 'Agenda e Eventos':[['13 SET · Sofia','Entrega 10:00','Confirmado'],['14 SET · Miguel','Retirada 09:00','Confirmado'],['19 SET · Ana & Lucas','Montagem 08:00','Planejamento']],
 'Estoque':[['Painel romano','4 disponíveis','Ativo'],['Cilindro decorativo','8 disponíveis','Ativo'],['Mesa boiserie','2 disponíveis','Ativo']],
 'Produção':[['Festa da Helena','18 de 25 itens','Em separação'],['15 anos · Sofia','25 de 25 itens','Pronto'],['Chá de bebê · Miguel','0 de 12 itens','Aguardando']],
 'Logística':[['Sofia','13/09 · 10:00','Confirmado'],['Miguel','14/09 · 09:00','Planejado'],['Ana & Lucas','19/09 · 08:00','Planejado']],
 'Financeiro':[['Contrato #1048','R$ 480','Vencido'],['Contrato #1047','R$ 650','Pendente'],['Logística · Sofia','R$ 180','A pagar']],
 'Gestão':[['Recebido no mês','R$ 11.620','Realizado'],['A receber','R$ 7.820','Aberto'],['Inadimplência','R$ 1.240','Atenção']],
 'Configurações':[['Modalidades','3 cadastradas','Configurar'],['Kits e serviços','12 cadastrados','Configurar'],['Equipe','4 usuários','Configurar']],
}

function HeavenDemo(){const [active,setActive]=useState('Hoje');return <div className="heaven-shell"><aside className="heaven-sidebar"><div className="heaven-brand">heaven<small>PLATAFORMA</small></div><nav className="heaven-nav">{modules.map(m=><button key={m} className={active===m?'active':''} onClick={()=>setActive(m)}>{m}</button>)}</nav><div className="heaven-company"><b>Ateliê Encanto Festas</b><br/>Ambiente demonstração</div></aside><main className="heaven-main"><Header active={active}/>{active==='Hoje'?<Today setActive={setActive}/>:<ModulePage name={active}/>}</main><nav className="heaven-mobile-nav">{['Hoje','CRM e Leads','Agenda e Eventos','Produção','Financeiro','Gestão'].map(m=><button key={m} className={active===m?'active':''} onClick={()=>setActive(m)}>{m}</button>)}</nav></div>}
function Header({active}:{active:string}){return <header className="heaven-header"><div><div className="heaven-eyebrow">Heaven Plataforma</div><h1 className="heaven-title">{active}</h1><div className="heaven-muted">ERP para empresas de decoração e locação de festas.</div></div><span className="heaven-pill">Demonstração</span></header>}
function Today({setActive}:{setActive:(s:string)=>void}){return <><div className="heaven-alert"><div><b>3 ações precisam de atenção hoje</b><div className="heaven-muted">Novo lead, separação pendente e recebimento vencido.</div></div><span className="heaven-pill">12 SET 2026</span></div><div className="heaven-grid heaven-kpis">{kpis.map(k=><section className="heaven-card" key={k[0]}><div className="heaven-muted">{k[0]}</div><div className="heaven-value">{k[1]}</div><div className="heaven-muted">{k[2]}</div></section>)}</div><div className="heaven-grid heaven-columns"><section className="heaven-card"><h2>Tarefas de hoje</h2><Task title="Novo lead — Mariana Alves" sub="Aniversário infantil · WhatsApp" action="Abrir CRM" go={()=>setActive('CRM e Leads')}/><Task title="Finalizar separação — Festa da Helena" sub="18 de 25 itens conferidos" action="Abrir produção" go={()=>setActive('Produção')}/><Task title="Recebimento vencido" sub="Contrato #1048 · R$ 480,00" action="Financeiro" go={()=>setActive('Financeiro')}/></section><section className="heaven-card"><h2>Próximos eventos</h2><Task title="13 SET · 15 anos — Sofia" sub="Entrega 10:00 · Montagem 11:30"/><Task title="14 SET · Chá de bebê — Miguel" sub="Retirada 09:00 · Devolução 15/09"/><Task title="19 SET · Casamento — Ana & Lucas" sub="Montagem completa · 08:00"/></section></div></>}
function Task({title,sub,action,go}:{title:string,sub:string,action?:string,go?:()=>void}){return <div className="heaven-task"><div><b>{title}</b><div className="heaven-muted">{sub}</div></div>{action&&<button onClick={go}>{action}</button>}</div>}
function ModulePage({name}:{name:string}){const data=rows[name]??[];return <section className="heaven-card" style={{marginTop:22}}><h2>{name}</h2><div className="heaven-muted" style={{marginBottom:14}}>Prévia navegável do módulo. A próxima conexão substituirá os dados fictícios pelos dados do tenant autenticado.</div>{data.length?<table className="heaven-table"><thead><tr><th>Registro</th><th>Informação</th><th>Status</th></tr></thead><tbody>{data.map((r,i)=><tr key={i}><td><b>{r[0]}</b></td><td>{r[1]}</td><td><span className="heaven-status">{r[2]}</span></td></tr>)}</tbody></table>:<div className="heaven-empty">Módulo em preparação.</div>}</section>}
