import { createFileRoute, Link } from '@tanstack/react-router'

export const Route = createFileRoute('/planos')({ component: PricingPage })

const LOGO='/heaven-logo.svg'
const founderFeatures=['Cadastro de clientes','Gestão de eventos','Agenda de festas','Controle de retiradas e devoluções','Cadastro de peças, temas e kits','Controle de disponibilidade do acervo','Criação de orçamentos','Geração de contratos','Controle de sinal, saldo e caução','Fluxo de caixa','Checklist de separação','Checklist de devolução','Registro de avarias e itens faltantes','Catálogo digital','Acesso pelo celular e computador','Atualizações do sistema','Suporte pelo WhatsApp']
const plans=[
 {name:'Heaven Essencial',price:'79,90',setup:'197',desc:'Ideal para quem deseja abandonar agendas, cadernos e planilhas.',users:'1 usuário',features:['Clientes e eventos','Agenda','Orçamentos','Contratos','Financeiro básico','Cadastro de até 150 itens','1 usuário'],annual:'R$ 799/ano'},
 {name:'Heaven Profissional',price:'129,90',setup:'297',desc:'Ideal para decoradoras que precisam controlar toda a operação e o acervo.',users:'Até 3 usuários',popular:true,features:['Todos os recursos do plano Essencial','Cadastro ampliado de peças e kits','Controle de disponibilidade','Checklist de retirada e devolução','Gestão de cauções, avarias e itens faltantes','Fluxo de caixa completo','Catálogo digital','Relatórios gerenciais','Até 3 usuários'],annual:'R$ 1.299/ano'},
 {name:'Heaven Premium',price:'189,90',setup:'497',desc:'Ideal para empresas estruturadas, com equipe e maior volume de eventos.',users:'Mais usuários',features:['Todos os recursos do plano Profissional','Mais usuários','Gestão de equipe e montagem','Recursos de logística','Catálogo personalizado com a marca da empresa','Automações de mensagens','Recursos de inteligência artificial','Relatórios avançados','Atendimento prioritário'],annual:'R$ 1.899/ano'}]
const faqs=[
 ['Preciso comprar o sistema?','Não. O ERP Heaven funciona por assinatura mensal ou anual. Enquanto sua assinatura estiver ativa, você terá acesso ao sistema, às atualizações e ao suporte correspondente ao seu plano.'],
 ['Existe taxa de implantação?','Sim. A implantação é paga uma única vez e contempla a configuração inicial da empresa, personalização e orientação para começar a utilizar o sistema.'],
 ['Posso cancelar quando quiser?','Sim. Durante o lançamento, a assinatura não terá fidelidade e poderá ser cancelada a qualquer momento.'],
 ['Funciona pelo celular?','Sim. O ERP Heaven será acessível pelo navegador no celular e no computador.'],
 ['O sistema serve para Peg & Monte?','Sim. O sistema foi desenvolvido para atender decoradoras, empresas de Peg & Monte, locadoras de peças e negócios que trabalham com decoração completa e montagem.'],
 ['Consigo controlar sinal, saldo e caução?','Sim. O financeiro do ERP Heaven permite acompanhar os valores recebidos, pendentes e relacionados à caução de cada evento.'],
 ['Consigo saber se uma peça está disponível?','Sim. O sistema controla a utilização das peças e kits por data para ajudar a evitar conflitos entre eventos.'],
 ['Meus dados ficam seguros?','Cada empresa acessa somente seus próprios dados. O ERP Heaven utiliza autenticação individual e armazenamento protegido das informações.']]

function PricingPage(){return <div className="pricing-page">
 <header className="landing-header new-header"><Link to="/" className="home-logo"><img src={LOGO} alt="Heaven ERP - Gestão de Festas e Decorações"/></Link><nav><Link to="/">Início</Link><a href="#fundadoras">Fundadoras</a><a href="#planos">Planos</a><a href="#faq">Dúvidas</a><Link to="/entrar">Entrar</Link></nav></header>
 <main>
  <section className="plans-hero"><span className="tag">PLANOS E PREÇOS</span><h1>Organize sua empresa de decoração<br/><em>do orçamento à devolução</em></h1><p>Clientes, eventos, contratos, acervo, pagamentos e operação reunidos em um sistema desenvolvido especialmente para decoradoras e empresas de Peg & Monte.</p></section>
  <section id="fundadoras" className="founder-wrap"><div className="founder-card"><div className="founder-main"><span className="launch-badge">CONDIÇÃO DE LANÇAMENTO</span><p className="plan-kicker">PLANO DE LANÇAMENTO</p><h2>Heaven Fundadoras</h2><p>Condição exclusiva para as primeiras clientes do ERP Heaven. O valor promocional será mantido por <b>12 meses</b> a partir da contratação.</p><div className="founder-price"><small>R$</small><strong>69,90</strong><span>/mês</span></div><div className="founder-setup">Implantação única de <b>R$ 197</b></div><a href="#interesse" className="primary-link">Quero ser uma Fundadora</a><small className="availability-note">A contratação será liberada quando todos os recursos anunciados estiverem operacionais.</small></div><div className="founder-features"><h3>Tudo o que você precisa para operar</h3><div className="feature-checks">{founderFeatures.map(x=><span key={x}>✓ {x}</span>)}</div></div></div>
  <div className="implementation"><div><span className="tag">IMPLANTAÇÃO</span><h2>Comece com a empresa configurada.</h2><p>A taxa única de R$ 197 inclui configuração inicial, personalização com nome, logotipo e informações comerciais, orientação para os primeiros cadastros, treinamento inicial e suporte durante a implantação.</p></div><div className="conditions"><b>Condições de lançamento</b><span>✓ Pagamento mensal recorrente</span><span>✓ Sem compra de licença vitalícia</span><span>✓ Sem fidelidade no período de lançamento</span><span>✓ Cancelamento a qualquer momento</span><span>✓ Dados disponíveis enquanto a assinatura estiver ativa</span><span>✓ Evolução contínua da plataforma</span></div></div>
  </section>
  <section className="brand-position"><span>HEAVEN ERP</span><h2>O sistema criado por quem vive a rotina de uma decoradora.</h2><h3>Da primeira conversa com a cliente até a devolução da última peça.</h3><p>O ERP Heaven entende as particularidades de quem trabalha com decoração, montagem e Peg & Monte. Controle kits, peças, contratos, pagamentos, cauções, retiradas, devoluções e conflitos de agenda em um único lugar.</p><b>Menos planilhas, menos esquecimentos e mais tempo para fazer sua empresa crescer.</b></section>
  <section id="planos" className="official-plans"><div className="plans-heading"><span className="tag">PLANOS OFICIAIS PREVISTOS</span><h2>Escolha a Heaven que acompanha o seu crescimento.</h2><p>Estes planos entrarão em vigor após o período de lançamento.</p></div><div className="plans-grid">{plans.map(p=><article className={`official-card ${p.popular?'popular':''}`} key={p.name}>{p.popular&&<span className="popular-badge">MAIS ESCOLHIDO</span>}<span className="soon-badge">EM BREVE</span><h3>{p.name}</h3><p>{p.desc}</p><div className="official-price"><small>R$</small><b>{p.price}</b><span>/mês</span></div><div className="official-setup">Implantação: R$ {p.setup}</div><hr/>{p.features.map(x=><span className="plan-feature" key={x}>✓ {x}</span>)}<div className="annual-price"><small>Opção anual</small><b>{p.annual}</b><span>Implantação cobrada separadamente</span></div></article>)}</div></section>
  <section className="annual-explain"><h2>Prefere pagar anualmente?</h2><p>Os planos oficiais também terão opção anual: Essencial por <b>R$ 799/ano</b>, Profissional por <b>R$ 1.299/ano</b> e Premium por <b>R$ 1.899/ano</b>. A taxa de implantação é cobrada separadamente.</p></section>
  <section id="faq" className="pricing-faq"><div><span className="tag">PERGUNTAS FREQUENTES</span><h2>Antes de começar, tire suas dúvidas.</h2></div><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
  <section id="interesse" className="founder-cta"><img src="/heaven-mark.svg" alt=""/><span className="tag">HEAVEN FUNDADORAS</span><h2>Garanta sua condição especial de lançamento.</h2><p>Participe da construção de um sistema feito por quem conhece de verdade a rotina das decoradoras.</p><a href="#fundadoras" className="primary-link">Quero ser uma Fundadora</a><small>Sem cobrança agora. A contratação será disponibilizada quando os recursos anunciados estiverem operacionais.</small></section>
 </main>
 <footer className="new-footer"><img src={LOGO} alt="Heaven ERP"/><div><b>Heaven ERP</b><p>Gestão de Festas e Decorações</p></div><span>Gestão profissional para quem transforma eventos em experiências.</span></footer>
 </div>}
