import { useState } from 'react'
import { useNavigate } from '@tanstack/react-router'
import { supabase } from '../../integrations/supabase/client'
type TrialSignupFormProps = { compact?: boolean }
export function TrialSignupForm({ compact = false }: TrialSignupFormProps) {
  const navigate=useNavigate();const[status,setStatus]=useState<'idle'|'loading'|'sent'>('idle');const[error,setError]=useState('')
  if(status==='sent')return <div className="trial-success"><strong>Confira seu e-mail</strong><p>Enviamos a confirmação do cadastro. Ao confirmar, você volta para a Heaven e seu ambiente de 15 dias será ativado.</p></div>
  async function handleSubmit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setError('');setStatus('loading');const form=new FormData(event.currentTarget),name=String(form.get('name')||'').trim(),companyName=String(form.get('companyName')||'').trim(),phone=String(form.get('phone')||'').trim(),email=String(form.get('email')||'').trim().toLowerCase(),city=String(form.get('city')||'').trim(),state=String(form.get('state')||'').trim().toUpperCase(),password=String(form.get('password')||'');const redirect=`${window.location.origin}/ativar`;const{data,error:signUpError}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:redirect,data:{full_name:name,company_name:companyName,phone,...(city?{city}:{}),...(state?{state}:{}),signup_source:'website',heaven_trial_signup:true}}});if(signUpError){setError(signUpError.message);setStatus('idle');return}if(data.session){const a=await supabase.rpc('activate_my_pending_trial');if(a.error){setError(a.error.message);setStatus('idle');return}navigate({to:'/app'});return}setStatus('sent')}
  return <form className={`trial-form${compact?' trial-form-compact':''}`} onSubmit={handleSubmit}><label>Seu nome<input required name="name" autoComplete="name" placeholder="Nome completo"/></label><label>Nome da empresa<input required name="companyName" autoComplete="organization" placeholder="Ex.: Encanto Festas"/></label><div className="form-grid"><label>WhatsApp<input required name="phone" inputMode="tel" autoComplete="tel" placeholder="(11) 99999-9999"/></label><label>E-mail<input required name="email" type="email" autoComplete="email" placeholder="voce@empresa.com"/></label></div>{!compact&&<div className="form-grid"><label>Cidade<input required name="city" autoComplete="address-level2" placeholder="Sua cidade"/></label><label>UF<input required name="state" autoComplete="address-level1" maxLength={2} placeholder="SP"/></label></div>}<label>Senha<input required name="password" type="password" minLength={8} autoComplete="new-password" placeholder="Mínimo de 8 caracteres"/></label>{error&&<div className="form-error">Não foi possível concluir o cadastro: {error}</div>}<button className="primary" type="submit" disabled={status==='loading'}>{status==='loading'?'Criando cadastro...':'Começar meus 15 dias grátis'}</button><small className="legal">Sem cobrança para iniciar. Após os 15 dias, a continuidade exige implantação e ativação de R$ 1.000,00 + mensalidade de R$ 99,90.</small></form>
}
